import Foundation
import Testing
@testable import WandelBar

@Test func systemArchiveCreatesListsAndExtractsOnePortableFile() throws {
    let root = FileManager.default.temporaryDirectory
        .appendingPathComponent(UUID().uuidString, isDirectory: true)
    let source = root.appendingPathComponent("source", isDirectory: true)
    let output = root.appendingPathComponent("Shared.wandelbar-presets")
    let extracted = root.appendingPathComponent("extracted", isDirectory: true)
    defer { try? FileManager.default.removeItem(at: root) }
    try FileManager.default.createDirectory(
        at: source.appendingPathComponent("textures", isDirectory: true),
        withIntermediateDirectories: true
    )
    try Data("{}".utf8).write(to: source.appendingPathComponent("manifest.json"))
    try Data([1, 2, 3]).write(to: source.appendingPathComponent("textures/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.png"))

    let archive = SystemPresetPackageArchive()
    try archive.createArchive(from: source, at: output)
    #expect(Set(try archive.listEntries(in: output)) == [
        "manifest.json", "textures/", "textures/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.png"
    ])
    try archive.extractArchive(at: output, to: extracted)
    #expect(try Data(contentsOf: extracted.appendingPathComponent("manifest.json")) == Data("{}".utf8))
}

@Test func systemArchiveRejectsStreamingExpansionAndTruncatedZIP() throws {
    let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
    defer { try? FileManager.default.removeItem(at: root) }
    let source = root.appendingPathComponent("source")
    try FileManager.default.createDirectory(at: source, withIntermediateDirectories: true)
    try Data(repeating: 65, count: 4096).write(to: source.appendingPathComponent("manifest.json"))
    let zip = root.appendingPathComponent("test.zip")
    try SystemPresetPackageArchive().createArchive(from: source, at: zip)
    let bounded = SystemPresetPackageArchive(limits: PresetPackageLimits(maximumPresets: 100, maximumTextures: 100, maximumCompressedBytes: 100000, maximumExtractedBytes: 100))
    #expect(throws: (any Error).self) { try bounded.extractArchive(at: zip, to: root.appendingPathComponent("out")) }
    let bytes = try Data(contentsOf: zip)
    try bytes.prefix(20).write(to: zip)
    #expect(throws: (any Error).self) { try SystemPresetPackageArchive().listEntries(in: zip) }
}

// Small real ZIP fixtures generated by Python zipfile, including Unix metadata.
@Test(arguments: [
    "UEsDBBQAAAAIAAAAIQBDv6ajBAAAAAIAAAANAAAAbWFuaWZlc3QuanNvbquuBQBQSwMEFAAAAAgAAAAhAIMW3IwDAAAAAQAAAAoAAAAuLi9lc2NhcGVkqwAAUEsBAhQDFAAAAAgAAAAhAEO/pqMEAAAAAgAAAA0AAAAAAAAAAAAAAKSBAAAAAG1hbmlmZXN0Lmpzb25QSwECFAMUAAAACAAAACEAgxbcjAMAAAABAAAACgAAAAAAAAAAAAAApIEvAAAALi4vZXNjYXBlZFBLBQYAAAAAAgACAHMAAABaAAAAAAA=" , // traversal
    "UEsDBBQAAAAIAAAAIQBdTPOkDgAAAAwAAAANAAAAbWFuaWZlc3QuanNvbtMvyS3QTy1OTixITQEAUEsBAhQDFAAAAAgAAAAhAF1M86QOAAAADAAAAA0AAAAAAAAAAAAAAP+hAAAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAEAAQA7AAAAOQAAAAAA" , // symlink
    "UEsDBBQAAAAIAAAAIQBDv6ajBAAAAAIAAAANAAAAbWFuaWZlc3QuanNvbquuBQBQSwMEFAAAAAgAAAAhAEO/pqMEAAAAAgAAAA0AAABtYW5pZmVzdC5qc29uq64FAFBLAQIUAxQAAAAIAAAAIQBDv6ajBAAAAAIAAAANAAAAAAAAAAAAAACkgQAAAABtYW5pZmVzdC5qc29uUEsBAhQDFAAAAAgAAAAhAEO/pqMEAAAAAgAAAA0AAAAAAAAAAAAAAKSBLwAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAIAAgB2AAAAXgAAAAAA" , // duplicate
    "UEsDBBQAAAAIAAAAIQAAAAAABAAAAAIAAAANAAAAbWFuaWZlc3QuanNvbquuBQBQSwECFAMUAAAACAAAACEAAAAAAAQAAAACAAAADQAAAAAAAAAAAAAApIEAAAAAbWFuaWZlc3QuanNvblBLBQYAAAAAAQABADsAAAAvAAAAAAA=" , // crc
    "UEsDBBQAAAAIAAAAIQAhEuAxCgQAAAEAEAANAAAAbWFuaWZlc3QuanNvbu3BMQEAAADCoGzrX8oQvkABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJwGUEsBAhQDFAAAAAgAAAAhACES4DEKBAAAAQAQAA0AAAAAAAAAAAAAAKSBAAAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAEAAQA7AAAANQQAAAAA" // expansion
])
func maliciousRealZIPIsRejectedAndExtractionRemoved(_ base64: String) throws {
    let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
    try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    defer { try? FileManager.default.removeItem(at: root) }
    let zip = root.appendingPathComponent("attack.zip")
    try #require(Data(base64Encoded: base64)).write(to: zip)
    let output = root.appendingPathComponent("output")
    #expect(throws: (any Error).self) { try SystemPresetPackageArchive().extractArchive(at: zip, to: output) }
    #expect(!FileManager.default.fileExists(atPath: output.path))
    #expect(!FileManager.default.fileExists(atPath: root.appendingPathComponent("escaped").path))
}

@Test func archiveRefusesExistingExtractionDestinationAndLinkedSources() throws {
    let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
    try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    defer { try? FileManager.default.removeItem(at: root) }
    let manifest = root.appendingPathComponent("manifest.json")
    try FileManager.default.createSymbolicLink(at: manifest, withDestinationURL: URL(fileURLWithPath: "/etc/hosts"))
    let zip = root.deletingLastPathComponent().appendingPathComponent(UUID().uuidString + ".zip")
    defer { try? FileManager.default.removeItem(at: zip) }
    #expect(throws: PresetPackageError.unsafeArchive) { try SystemPresetPackageArchive().createArchive(from: root, at: zip) }
    #expect(throws: PresetPackageError.unsafeArchive) { try SystemPresetPackageArchive().extractArchive(at: zip, to: root) }
}
